First Laba
secourse2019/tortuga-software-engineeering pull request #13
Opened 2019-09-11 21:23 UTC by Kilomaster3

ДЗ

2019-09-12 08:23 UTC, secourse2019 requested changes
ну ты понел

2019-09-12 08:23 UTC, secourse2019 commented on Grom/ZKAI/Laba1/company/Task10.java
> +    public double task_10(double n){
int n

2019-09-12 08:23 UTC, secourse2019 commented on Grom/ZKAI/Laba1/company/Task11.java
> +        System.out.println(b.task_11(10));
what is 10?

2019-09-12 08:23 UTC, secourse2019 commented on Grom/ZKAI/Laba1/company/Task11.java
> +        System.out.println(b.task_11(10));
int n = Integerer.valueOf(args[0])

2019-09-12 08:23 UTC, secourse2019 commented on Grom/ZKAI/Laba1/company/Task12.java
> +    public double task_12(double n) {
function naming

2019-09-15 16:12 UTC, secourse2019 requested changes
pull code from upstream master and update code

2019-09-15 16:12 UTC, secourse2019 commented on Grom/ZKAI/Laba1/company/Task14.java
> +    public double Task_14(int s){
static will be better

2019-09-15 16:12 UTC, secourse2019 commented on Grom/ZKAI/Laba1/company/Task14.java
> +        System.out.println(b.Task_14(3));
with static usage will Task_14.Task_14(3)

2019-09-15 17:06 UTC, ALHrom reviewed
Новое

2019-09-15 21:29 UTC, merged