Second laba
secourse2019/tortuga-software-engineeering pull request #40
Opened 2019-09-25 14:03 UTC by VALIKKKKK

Second laba implementation

2019-09-25 20:03 UTC, secourse2019 requested changes
remove trash

2019-10-01 08:23 UTC, Kujatata commented on Kashko/second laba/src/com/company/Main.java
> +}
the Main class is not used

2019-10-01 08:23 UTC, Kujatata commented on Kashko/second laba/src/com/company/Transport/dpo/geolocation/Geolocation.java
> +
unwanted empty string

2019-10-01 20:41 UTC, secourse2019 approved these changes

2019-10-01 20:42 UTC, merged