Vantuz lab3
secourse2019/tortuga-software-engineeering pull request #55
Opened 2019-09-30 23:51 UTC by ivanko337

2019-10-01 11:12 UTC, secourse2019 requested changes
I'd like to see only source files (how to fix it, see Kate's PR)

too many duplicates

fix comments

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Blogger.cs
> +        public void SlapInPassager(Passager passager)
Passenger)

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Blogger.cs
> +using System.Linq;
remove unused imports

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Bus.cs
> +        { }
bus cannot fill fuel itself

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Driver.cs
> +using System.Threading.Tasks;
remove unused imports

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Driver.cs
> +        public void FillFuel()
pass Vehicle as parameter here

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Electrobus.cs
> +    {
add constructor at least...

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/GroundTransport.cs
> +        public List<Blogger> Bloggers { get; set; }
do you mean that bloggers will be at vehicle all the way? if not, remove it

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/GroundTransport.cs
> +        public GroundTransport(Driver driver, List<DateTime> timetable, int amount, int stock)
add these params as class fields

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Passager.cs
> +        public void Payed()
what is responsibility of that method?

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Passager.cs
> +        public Passager(Transport transport)
passenger will not always be in the transport, so remove that param and add base call at least

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Subway.cs
> +        public Turnstiles Turnstiles { get; private set; }
plural form means that you have to declare List<Turnstile>, do not complicate your code

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Transport.cs
> +        public List<DateTime> Timetable { get; private set; }
may be Dictionary<DateTime, Station> will be more applicable here?

2019-10-01 11:12 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Worker.cs
> +        public Worker(int salary)
how about base call?

2019-10-01 20:28 UTC, ivanko337 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Driver.cs
> +        public void FillFuel()
> 
> 
> pass Vehicle as parameter here

it's redundant, Transport class have property TransportDriver

2019-10-01 20:28 UTC, ivanko337 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/GroundTransport.cs
> +        public List<Blogger> Bloggers { get; set; }
> 
> 
> do you mean that bloggers will be at vehicle all the way? if not, remove it

no, that code able to add and remove bloggers from vehicle

2019-10-01 20:28 UTC, ivanko337 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Transport.cs
> +        public List<DateTime> Timetable { get; private set; }
> 
> 
> may be Dictionary<DateTime, Station> will be more applicable here?

if comeone need to check timetable, he can print all timetable. like at transport stations

2019-10-02 11:16 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/GroundTransport.cs
> +        public List<Blogger> Bloggers { get; set; }
ok

2019-10-02 11:17 UTC, secourse2019 commented on UML_vantuz/FIrstUMLLab/FIrstUMLLab/Transport.cs
> +        public List<DateTime> Timetable { get; private set; }
you can still print the keys from dict

2019-10-02 20:49 UTC, secourse2019 approved these changes

2019-10-02 20:49 UTC, merged