adding transport's files
secourse2019/tortuga-software-engineeering pull request #59
Opened 2019-10-01 12:13 UTC by CrazyPl0yer

2019-10-01 19:43 UTC, secourse2019 requested changes
check other's PR's

2019-10-02 17:08 UTC, secourse2019 approved these changes
ok for now

2019-10-02 17:08 UTC, secourse2019 commented on Davydov/Transport/dpo/Depo.java
> +import java.util.AbstractList;
just list

2019-10-02 17:10 UTC, Kjatata approved these changes
Sup

2019-10-02 17:10 UTC, merged